config/routes.rb
Rails.application.routes.draw do
  resources :trendiness
  resources :grades
  resources :writers do
    member do
      get :choose
      post :apply
    end
  end

  root 'home#index'
end

app/models/most_wanted.rb
# == Schema Information
#
# Table name: most_wanteds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  percentage :float
#

class MostWanted < ActiveRecord::Base
end

app/models/popular.rb
# == Schema Information
#
# Table name: populars
#
#  id         :integer          not null, primary key
#  name       :string
#  percentage :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Popular < ActiveRecord::Base
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  name       :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  writer_id  :integer
#

class Recipe < ActiveRecord::Base
  belongs_to :writer

  def stripped_content
    ActionController::Base.helpers.strip_tags(content)
  end

  def words_count
    stripped_content.split.size
  end

  def characters_count
    stripped_content.gsub(" ","").size
  end

  def sentences_count
    stripped_content.scan(/[^\.!?;]+[\.!?;]/).map(&:strip).count
  end
end

app/models/trendy.rb
# == Schema Information
#
# Table name: trendies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  percentage :float
#

class Trendy < ActiveRecord::Base
end

app/models/writer.rb
# == Schema Information
#
# Table name: writers
#
#  id           :integer          not null, primary key
#  name         :string
#  grade_points :integer
#  grande_label :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Writer < ActiveRecord::Base
  has_many :recipes, dependent: :destroy

  # https://en.wikipedia.org/wiki/Automated_readability_index
  GRADES = {
    grade_1: "Kindergarten",
    grade_2: "1st",
    grade_3: "2nd",
    grade_4: "3rd",
    grade_5: "4th",
    grade_6: "5th",
    grade_7: "6th",
    grade_8: "7th",
    grade_9: "8th",
    grade_10: "9th",
    grade_11: "10th",
    grade_12: "11th",
    grade_13: "12th",
    grade_14: "College"
  }

  def grade
    return grade_points if grade_points
    result = 4.71*(average_characters_count_per_recipe/average_words_count_per_recipe) + 0.5*(average_words_count_per_recipe/average_sentences_count_per_recipe) - 21.43
    result <= 11 ? (result + 3).to_i : result.to_i
    key = "grade_#{result.to_i}".to_sym
    update(grade_points: result,grande_label: Writer::GRADES[key])
  end

  def average_characters_count_per_recipe
    recipes.map(&:characters_count).reduce(:+)/recipes.count
  end

  def average_words_count_per_recipe
    recipes.map(&:words_count).reduce(:+)/recipes.count
  end

  def average_sentences_count_per_recipe
    recipes.map(&:sentences_count).reduce(:+)/recipes.count
  end

  def skills_list
    skills.downcase.split(',')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  #$automated_readability_index = 4.71* (@characters/@words) + 0.5 * (@words/@sentences) - 21.43

  def index
    skill = params[:skill].downcase
    @writers = Writer.all
    @data = []
    @writers.each do |writer|
      if writer.skills_list.include?(skill)
        @data << {id: writer.id, name: writer.name, grade: writer.grade, photo: writer.photo}
      end
    end
    respond_to do |format|
      format.js
    end
  end
end

# Score Age Grade Level
# 1 5-6 Kindergarten
# 2 6-7 First Grade
# 3 7-8 Second Grade
# 4 8-9 Third Grade
# 5 9-10  Fourth Grade
# 6 10-11 Fifth Grade
# 7 11-12 Sixth Grade
# 8 12-13 Seventh Grade
# 9 13-14 Eighth Grade
# 10  14-15 Ninth Grade
# 11  15-16 Tenth Grade
# 12  16-17 Eleventh grade
# 13  17-18 Twelfth grade
# 14  18-22 College

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @trendy = Trendy.all
    @popular = Popular.all
    @most_wanted = MostWanted.all
  end
end

app/controllers/trendiness_controller.rb
class TrendinessController < ApplicationController

  def index
    #https://api.stackexchange.com/2.2/tags?order=desc&sort=popular&site=stackoverflow
    @conn = Faraday.new(:url => 'https://api.stackexchange.com/2.2/') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    response = @conn.get 'tags?order=desc&sort=popular&site=stackoverflow', { order: "desc", sort: "popular", site: "stackoverflow"}

    trendy = JSON.parse(response.body)

    render json: trendy
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController

  def choose
    @writer = Writer.find(params[:id])
    @skills = @writer.skills_list.map{|s|"##{s}"}.join(', ')
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trendiness_helper.rb
module TrendinessHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/grades/_author.html.erb
<li class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="<%= author[:photo] %>" alt="author1">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to author[:name], choose_writer_path(id:author[:id]), remote: true, onclick: "showSpinner();" %>
    </h4>
    <div class="progress">
      <div class="progress-bar progress-bar-success" style="width: 35%"></div>
      <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 40%"></div>
      <div class="progress-bar progress-bar-danger" style="width: 10%"></div>
    </div>
    <p>
      <%="Hold the door... " * 16 %>
    </p>
  </div>
</li>
<hr>

app/views/grades/index.js.erb
$('.js-authors-listing > ul').html("");
<% @data.each do |data| %>
  var author = '<%= j render "grades/author", author: data %>';
  $('.js-authors-listing > ul').append(author);
<% end %>
$('.js-authors-listing').show();
$('.spinner').hide();
$('.js-dont-apply').click();

app/views/home/index.html.erb
<div class="spinner"><i class="fa fa-circle-o-notch fa-spin fa-2x" aria-hidden="true"></i></div>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <h1><a href="/" style="padding-left: 4px; color: #70CCCC;">AskHodor</a></h1>
    <ol class="breadcrumb" style="padding-left: 15px;">
      <li><a href="#" class="js-trendy" role="tab" data-toggle="tab">Trendy</a></li>
      <li><a href="#" class="js-popular" role="tab" data-toggle="tab">Popular</a></li>
      <li><a href="#" class="js-most-wanted" role="tab" data-toggle="tab">Most Wanted</a></li>
    </ol>
  </div>
</nav>

<div class="container" style="margin-top: 150px;">
  <div class="row">
    <div class="col-md-3">
      <ul class="list-group js-list js-trendy-list">
        <% @trendy.each do |trendy| %>
          <li class="list-group-item">
            <span class="badge"><%= trendy.percentage %>%</span>
            <%= link_to trendy.name, grades_path(skill: trendy.name), remote: true, onclick: "showSpinner();"%></a>
          </li>
        <% end %>
      </ul>
     <ul class="list-group js-list js-popular-list" hidden>
       <% @popular.each do |popular| %>
          <li class="list-group-item">
            <span class="badge"><%= popular.percentage %>%</span>
            <%= link_to popular.name, grades_path(skill: popular.name), remote: true, onclick: "showSpinner();"%></a>
          </li>
        <% end %>
     </ul>
     <ul class="list-group js-list js-most-wanted-list" hidden>
        <% @most_wanted.each do |most_wanted| %>
          <li class="list-group-item">
            <span class="badge"><%= most_wanted.percentage %>%</span>
            <%= link_to most_wanted.name, grades_path(skill: most_wanted.name), remote: true, onclick: "showSpinner();"%></a>
          </li>
        <% end %>
     </ul>
    </div>

    <div class="col-md-6 js-authors-listing" hidden>
      <ul class="media-list">
        <hr style="margin-top: 0px;">
      </ul>

      <nav style="margin-left: 25%;">
        <ul class="pagination">
          <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
          <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
          <li><a href="#">2 <span class="sr-only">(current)</span></a></li>
          <li><a href="#">3 <span class="sr-only">(current)</span></a></li>
          <li><a href="#">4 <span class="sr-only">(current)</span></a></li>
          <li><a href="#">5 <span class="sr-only">(current)</span></a></li>
          <li><a href="#">6 <span class="sr-only">(current)</span></a></li>
          <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&raquo;</span></a></li>
        </ul>
      </nav>
    </div>
    <div class="col-md-3 js-apply" hidden>
      <div class="ribbon-wrapper-green"><div class="ribbon-green"><span class="js-grade-label"> </span><i class="fa fa-graduation-cap" aria-hidden="true"></i>
</div></div>
      <div class="jumbotron">
        <img class="media-object img-rounded js-apply-image" src="assets/author0.jpg" alt="author1" style="margin:0 auto;">
        <p class="text-center js-apply-tags" style="padding-top: 33px;"></p>
        <p style="padding-top: 33px; margin-left: 24%; margin-bottom: 3%;"><a class="btn btn-pr ry btn-lg js-apply-btn" href="#" role="button">Apply Here</a></p>
        <p style="margin-left: 20%;"><a class="btn btn-danger btn-lg js-dont-apply" href="#" role="button">Or Just Don't</a></p>
      </div>
    </div>
  </div>
</div>

<!-- The content of your page would go here. -->

  <footer class="footer-distributed">
      <div class="footer-left">
        <h3>Company<span>logo</span></h3>
        <p class="footer-links">
          <a href="#">Home</a>
          ·
          <a href="#">Blog</a>
          ·
          <a href="#">Pricing</a>
          ·
          <a href="#">About</a>
          ·
          <a href="#">Faq</a>
          ·
          <a href="#">Contact</a>
        </p>
        <p class="footer-company-name">askhodor.Inc &copy; 2016</p>
       <div class="footer-icons">
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-github"></i></a>
        </div>
      </div>
      <div class="footer-right">
        <p>Don't Fuck With Us:</p>
        <form action="#">
          <input type="text" name="email" placeholder="Email" />
          <textarea name="message" placeholder="Message"></textarea>
          <button class="you-wish">Send</button>
        </form>
      </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AskHodor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://use.fontawesome.com/d211aa578b.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/writers/choose.js.erb
$('.js-apply-image').attr('src','<%= @writer.photo %>');
$('.js-apply-tags').html('<%= @skills %>');
$('.js-grade-label').html('<%= @writer.grande_label %> ')
$('.js-apply').removeAttr('hidden');
$('.spinner').hide();